### ISSUE TITLE
No CSS included

### ISSUE THREAD

**Issue by patrickleemsantos** [TappNetwork/nova-select-country-code#1]
Theres no CSS on the field

**Comment by andreia** [comment]
@patrickleemsantos Thanks for reporting :)

The [Vue Select](https://vue-select.org) dependency was missing. Just updated `package.json` to include it and the `vue-select` CSS has been added.

It's released on [v1.1](https://github.com/TappNetwork/nova-select-country-code/releases/tag/v1.1)

Also updated the installation instructions to run the command below to publish the assets (svg flags):

```bash
php artisan vendor:publish --tag=public --force
```
